# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

model:
  _component_: models.mmllama3_8b
  perception_tokens: 2

image_bind:
  _component_: models.imagebind_huge

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: output/Meta-Llama-3-8B-Instruct/
  checkpoint_files: [
    meta_model_0.pt
  ]
  output_dir: output/Meta-Llama-3-8B-Instruct/
  model_type: LLAMA3

tokenizer:
  _component_: models.a2a_tokenizer
  path: checkpoints/Meta-Llama-3-8B-Instruct/tokenizer.model

# Environment
device: cuda
dtype: bf16
seed: 217


# LLM Eval specific eval args
model_name: mmllama
tasks: [
  realworldqa,
  # llava-bench-coco
  # mmmu
]
limit: null
max_seq_length: 4096
batch_size: 4

# Quantization specific args
quantizer: null

temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300
